### PR TITLE
remove deprecated api url #101

### LINKED ISSUE #101: [change] Remove deprecated receive API URL
Remove the deprecated `/receive/{id}` URL and its related deprecation warning.

See https://github.com/openwisp/openwisp-network-topology/pull/79 and https://github.com/openwisp/openwisp-network-topology/issues/62 for more info.

### PR DESCRIPTION
**Pull request by prajwal296**
closes #101

### CODE REVIEW

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
The build is failing for style issues, please run `openwisp-qa-format` and then `./run-qa-checks` before committing and pushing. 

Please amend your commit according to the contributing guidelines: https://openwisp.io/docs/developer/contributing.html.

**Comment by nemesisdesign** [comment]
@prajwal296 not working on this anymore?

**Comment by devkapilbansal** [comment]
@nemesisdesign this PR is stale as the fork is deleted

**Review by nemesisdesign — APPROVED** [review]
The code is fine, it was just the commit message but I can fix that while merging. I assume @prajwal296 is not interested in contributing anymore so we can merge and fix the patch ourselves. Thanks anyway @prajwal296.

**Pull request merged**
