### PR TITLE
[qa] Added pending migration check to .travis.yml

### PR DESCRIPTION
**Pull request by rohithasrk**
Can be merged after https://github.com/openwisp/openwisp-users/pull/19 is merged.

### CODE REVIEW

**Comment by nemesisdesign** [comment]
This is how I fixed it in openwisp-controller: https://github.com/openwisp/openwisp-controller/blob/master/.travis.yml#L44
I wish I knew why is happening

**Comment by nemesisdesign** [comment]
Is it because of this? https://github.com/openwisp/openwisp-users/pull/19

**Comment by rohithasrk** [comment]
Yes. I think the AbstractUser in django 2.0 and django 1.11 have different fields for last_name. Therefore I just overrided and gave them a default.

**Comment by nemesisdesign** [comment]
:+1:

**Pull request merged**
