### PR TITLE
[change] Integrate latest version of netjsongraph.js #149

### LINKED ISSUE #149: [change] Use new version of netjsongraph.js
We have to update this module to use the new and improved version of [netjsongraph.js](https://github.com/openwisp/netjsongraph.js).

### PR DESCRIPTION
**Pull request by totallynotvaishnav**
#### To do
- [x] Improve date picker UI
- [x] Parse dates using date parse function
- [x] Add tests if any

closes #149

### CODE REVIEW

**Comment by totallynotvaishnav** [comment]
### Screenshot
Screenshot 2022-07-28 at 10 44 27 PM
Screenshot 2022-07-28 at 10 44 47 PM

**Comment by mwarning** [comment]
Hi, there is small issue that can be seen at https://demo.openwisp.io/admin/topology/topology/6c04a21b-30d9-48f3-8757-023cb6328731/change/

1. click on "View topology graph" => there is nice star link graph
2. close the graph with big white X in the top right corner => you get
back to management panel
3. click on "View topology graph" again => no topology is loaded

**Comment by totallynotvaishnav** [comment]
> Hi, there is small issue that can be seen at https://demo.openwisp.io/admin/topology/topology/6c04a21b-30d9-48f3-8757-023cb6328731/change/
> 
> 1. click on "View topology graph" => there is nice star link graph
> 2. close the graph with big white X in the top right corner => you get
>    back to management panel
> 3. click on "View topology graph" again => no topology is loaded

Seems like a bug. I will look into this.

**Review by nemesisdesign — COMMENTED** [review]
This looks good! Let's leave it open until we get some more PRs on the library merged so we can include support for narrow screens.

I also want to do some minor style improvements to this PR as soon as I have a chance.

**Comment by nemesisdesign** [comment]
Merged in #153, thanks!

**Pull request closed without merging**
