### PR TITLE
Integrate visualizer into the application

### PR DESCRIPTION
**Pull request by rohithasrk**
References #6. As of now, nothing has been done. Just added the django_netjsongraph dev to travis build and a test visualizer app.

### CODE REVIEW

**Comment by nemesisdesign** [comment]
@rohithasrk you could start with the "view on site" button, for example.

**Comment by rohithasrk** [comment]
@nemesisdesign Added the necessary code required. Now, there's a visualize topology button in the change topology window as well as a link to the frontend. There are some bugs I've discovered. Shall fix them ASAP.

**Comment by nemesisdesign** [comment]
@rohithasrk what bugs?

**Comment by rohithasrk** [comment]
@nemesisdesign That was six days ago. :stuck_out_tongue:

**Comment by rohithasrk** [comment]
@nemesisdesign Can this be merged?

**Pull request merged**
